electricity <- read.table("ExData_Plotting1-master/household_power_consumption.txt", sep = ";", header = TRUE)
temp <- subset(electricity, as.Date(Date, "%d/%m/%Y") >= "2007-02-01" &  as.Date(Date, "%d/%m/%Y") <= "2007-02-02" )
temp1 <- temp %>% filter(Global_active_power != "?")
temp1$Time <- strptime(paste(temp1$Date, temp1$Time), "%d/%m/%Y %H:%M:%S")
plot(temp1$Time, temp1$Sub_metering_1, type = "l", xlab = "", ylab = "Energy Sub Metering")
lines(temp1$Time, temp1$Sub_metering_2, type = "l", col = "red")
lines(temp1$Time, temp1$Sub_metering_3, type = "l", col = "blue")
legend ("topright", col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"), lty = c(1,1,1), cex = 0.5)
dev.copy(device = png, 'plot3.png', width = 480, height = 480)
dev.off()