electricity <- read.table("ExData_Plotting1-master/household_power_consumption.txt", sep = ";", header = TRUE)
temp <- subset(electricity, as.Date(Date, "%d/%m/%Y") >= "2007-02-01" &  as.Date(Date, "%d/%m/%Y") <= "2007-02-02" )
temp1 <- temp %>% filter(Global_active_power != "?")
hist(as.numeric(temp1$Global_active_power), col = "red", main = "Global Active Power", xlab = "Global Active Power (killowatts)")
dev.copy(device = png, 'plot1.png', width = 480, height = 480)
dev.off()